#!/bin/sh

case $BLOCK_BUTTON in
    1 | 2 | 3)
        pkill -9 zoom
        ;;
esac


# Check if Zoom is running
if pgrep -x "zoom" > /dev/null; then
    status="‼️"
fi

# Print the status inside a span
printf "<span>%s</span>\n" "$status"
echo
