#!/bin/sh
# Arguments:
# 1: icon
# 2: color

def_icon=
def_col=#fff
icon=${1:-$def_icon}
col=${2:-$def_col}


case $BLOCK_BUTTON in
	1 | 2 | 3)
        notify-send "$icon Memory hogs (%)" "$(ps axch -o cmd:10,pmem k -pmem | head | awk '$0=$0' )"
        ;;
esac

# Get used and total memory (in bytes)
read used total < <(free -b | awk '/^Mem:/ {print $3, $2}')

# Calculate the percentage of memory used
percent=$(awk -v used="$used" -v total="$total" 'BEGIN { printf "%.0f", (used/total)*100 }')

# Determine the background color based on the percentage
if [ "$percent" -lt 50 ]; then
    col="#23A767"  # green for less than 50%
elif [ "$percent" -lt 80 ]; then
    col="#feb000"  # yellow for between 50% and 80%
else
    col="#FF0000"  # red for more than 80%
fi

# printf "<span background='$bg_color' color='$col'>"
printf "<span color='$col'>"
	printf " $icon "
	printf  $(free -h --si | awk '/^Mem:/ {print $3 "/" $2}')
	printf " "
printf "</span>"
echo
