#!/bin/sh
# Arguments:
# 1: color

col=${1:-#fff}

case $BLOCK_BUTTON in
    1 | 2 | 3)
        notify-send "$icon CPU hogs (%)" "$(
            ps axch -o cmd:10,pcpu k -pcpu \
            | grep -v '^ps\b' \
            | head \
            | awk '$0=$0'
        )"
        ;;
esac

# Define array
ramp_arr=(▁ ▂ ▃ ▄ ▅ ▆ ▇ █)

printf "<span color='$col'>"
sar -P ALL 1 1 | grep -E 'Average:\s+[0-9]+' | while read -r line ; do
    val=$(echo $line | awk '{cpu_usage=$3} END {printf "%0.2f", cpu_usage}')
    idx=`echo "scale=4; $val/14.3" | bc`
    intidx=`echo "$idx/1" | bc`
    printf "${ramp_arr[$intidx]}"
done
printf "</span>"
echo
